Check response value after bundle upload

diff --git a/.github/workflows/make-release.yml b/.github/workflows/make-release.yml
--- a/.github/workflows/make-release.yml
+++ b/.github/workflows/make-release.yml
@@ -43,8 +43,12 @@ jobs:
             echo "Invalid editId" >&2
             exit 1
           fi
-          curl -X POST -F 'file=@./build/app/outputs/bundle/release/app-release.aab' -H "Authorization: Bearer $token" https://www.googleapis.com/androidpublisher/v3/applications/org.fitrecord.android.release/edits/${edit_id}/bundles?uploadType=media
-          echo "Upload status $?"
+          version_code=$(curl -X POST -F 'file=@./build/app/outputs/bundle/release/app-release.aab;type=application/octet-stream' -H "Authorization: Bearer $token" https://www.googleapis.com/androidpublisher/v3/applications/org.fitrecord.android.release/edits/${edit_id}/bundles?uploadType=media | jq -r .versionCode)
+          if [ -z "version_code" ]
+          then
+            echo "Invalid versionCode" >&2
+            exit 1
+          fi
           curl -X POST -d '{}' -H "Authorization: Bearer $token" -H "Content-Type: application/json" https://www.googleapis.com/androidpublisher/v3/applications/org.fitrecord.android.release/edits/${edit_id}:commit
           echo "Commit status $?"
       - name: Create Release
