Add exit status checks

diff --git a/.github/workflows/make-release.yml b/.github/workflows/make-release.yml
--- a/.github/workflows/make-release.yml
+++ b/.github/workflows/make-release.yml
@@ -31,10 +31,22 @@ jobs:
         run: ~/.flutter_dist/bin/flutter build appbundle --build-name=${{ steps.set_env.outputs.SOURCE_TAG }} --build-number=${{ steps.set_env.outputs.BUILD_NUMBER }}
       - name: Create Play Store edit
         run: |
-          token=`bash ./.github/workflows/make-google-api-token.sh "https://www.googleapis.com/auth/androidpublisher" "${{ secrets.PLAY_STORE_SERVICE_EMAIL }}" "${{ secrets.PLAY_STORE_SERVICE_KEY }}"`
-          edit_id=`curl -X POST -d '{}' -H "Authorization: Bearer $token" -H "Content-Type: application/json" https://www.googleapis.com/androidpublisher/v3/applications/org.fitrecord.android.release/edits | jq -r .id`
+          token=$(bash ./.github/workflows/make-google-api-token.sh "https://www.googleapis.com/auth/androidpublisher" "${{ secrets.PLAY_STORE_SERVICE_EMAIL }}" "${{ secrets.PLAY_STORE_SERVICE_KEY }}")
+          if [ $token == 'null' ]
+          then
+            echo "Invalid token"
+            exit 1
+          fi
+          edit_id=$(curl -X POST -d '{}' -H "Authorization: Bearer $token" -H "Content-Type: application/json" https://www.googleapis.com/androidpublisher/v3/applications/org.fitrecord.android.release/edits | jq -r .id)
+          if [ -z $edit_id ]
+          then
+            echo "Invalid editId"
+            exit 1
+          fi
           curl -X POST -F 'data=@./build/app/outputs/bundle/release/app-release.aab' -H "Authorization: Bearer $token" https://www.googleapis.com/androidpublisher/v3/applications/org.fitrecord.android.release/edits/$(edit_id)/bundles?uploadType=media
+          echo "Upload status $?"
           curl -X POST -d '{}' -H "Authorization: Bearer $token" -H "Content-Type: application/json" https://www.googleapis.com/androidpublisher/v3/applications/org.fitrecord.android.release/edits/$(edit_id):commit
+          echo "Commit status $?"
       - name: Create Release
         id: create_release
         uses: actions/create-release@v1.1.1
