Fix bash errors

diff --git a/.github/workflows/make-release.yml b/.github/workflows/make-release.yml
--- a/.github/workflows/make-release.yml
+++ b/.github/workflows/make-release.yml
@@ -32,15 +32,15 @@ jobs:
       - name: Create Play Store edit
         run: |
           token=$(bash ./.github/workflows/make-google-api-token.sh "https://www.googleapis.com/auth/androidpublisher" "${{ secrets.PLAY_STORE_SERVICE_EMAIL }}" "${{ secrets.PLAY_STORE_SERVICE_KEY }}")
-          if [ $token == 'null' ]
+          if [ $token == "null" ]
           then
-            echo "Invalid token"
+            echo "Invalid token" >&2
             exit 1
           fi
           edit_id=$(curl -X POST -d '{}' -H "Authorization: Bearer $token" -H "Content-Type: application/json" https://www.googleapis.com/androidpublisher/v3/applications/org.fitrecord.android.release/edits | jq -r .id)
-          if [ -z $edit_id ]
+          if [ -z "$edit_id" ]
           then
-            echo "Invalid editId"
+            echo "Invalid editId" >&2
             exit 1
           fi
           curl -X POST -F 'data=@./build/app/outputs/bundle/release/app-release.aab' -H "Authorization: Bearer $token" https://www.googleapis.com/androidpublisher/v3/applications/org.fitrecord.android.release/edits/$(edit_id)/bundles?uploadType=media
